import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Topbar } from "../components/topbar/topbar";
import { Dimmer } from "@/components/overlays/dimmer";
import { SleepOverlay } from "@/components/overlays/sleep";
import { NotificationOverlay } from "@/components/overlays/notification";
import { NotificationProvider } from "@/context/NotificationContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} h-screen w-screen bg-gray-950 text-white antialiased`}
			>
				<NotificationProvider>
					<Topbar />
					<main className="h-[calc(100vh-4rem)]">{children}</main>
				</NotificationProvider>
			</body>
		</html>
	);
}
